export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const FETCH_BASKET = 'FETCH_BASKET';
export const COUNT_COST='COUNT_COST';
export const DELETE_PRODUCT_FROM_BASKET='DELETE_PRODUCT_FROM_BASKET';
export const UPDATE_PRODUCT_FROM_BASKET='UPDATE_PRODUCT_FROM_BASKET';


export const FETCH_CATEGORIES='FETCH_CATEGORIES';
export const CREATE_CATEGORY='CREATE_CATEGORY';
export const GET_CATEGORIES='GET_CATEGORIES';
export const GET_TYPES_BY_CATEGORY_ID='GET_TYPES_BY_CATEGORY_ID';
export const SET_TYPE='SET_TYPE';
export const SET_CATEGORY='SET_CATEGORY';
export const SET_ACTIVE_TYPE='SET_ACTIVE_TYPE';
export const CLEAR_ACTIVE_TYPE='CLEAR_ACTIVE_TYPE';
export const DELETE_ACTIVE_TYPE='DELETE_ACTIVE_TYPE';
export const SET_ACTIVE_CATEGORY='SET_ACTIVE_CATEGORY';
export const DELETE_ACTIVE_CATEGORY='DELETE_ACTIVE_CATEGORY';
export const EDIT_ACTIVE_CATEGORY='EDIT_ACTIVE_CATEGORY';
export const EDIT_ACTIVE_TYPE='EDIT_ACTIVE_TYPE';

export const CLEAR_PRODUCTS='CLEAR_PRODUCTS';
export const SAVE_PRODUCT='SAVE_PRODUCT';
export const FETCH_PRODUCTS='FETCH_PRODUCTS';
export const EDIT_NEW_PRODUCT='EDIT_NEW_PRODUCT';
export const EDIT_PRODUCT='EDIT_PRODUCT';
export const SET_PRODUCT='SET_PRODUCT';
export const DELETE_PRODUCT='DELETE_PRODUCT';
